[phases.setup]
nixPkgs = ['php83', 'php83Extensions.pgsql', 'php83Extensions.pdo_pgsql', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.dom', 'php83Extensions.curl', 'php83Extensions.zip', 'php83Extensions.gd', 'php83Extensions.fileinfo', 'nodejs_20', 'npm-9_x']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm ci']

[phases.build]
cmds = ['npm run build', 'php artisan optimize']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'
